language: go

go:
  - '1.12.x'

services:
  - docker

before_install:
  - docker build -t vinchauhan/two-f-gates:$BRANCH .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master