language: go

go:
  - '1.12.x'

#script:
#  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
#  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

services:
  - docker

before_install:
  - docker build -t vinchauhan/two-f-gates:$BRANCH .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master